version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=stdnt_reg
      - MYSQL_ROOT_PASSWORD=<password>
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/migration/dump.sql:/docker-entrypoint-initdb.d/dump.sql
volumes:
  db:
    driver: local
