version: "3"

services:
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.10.2'
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - "ELASTIC_APM_SERVER_URL=http://localhost:8200"
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: 'docker.elastic.co/kibana/kibana:7.10.2'
    ports:
      - "5601:5601"
    hostname: kibana
    depends_on:
      - elasticsearch

volumes:
  esdata:
    driver: local