server:
  address: 5005
database:
  host: "docker.for.mac.localhost"
  port: "3306"
  dbName: "stdnt_reg"
  user: "root"
  pass: ""
cors:
  allowOrigins: "*"
jwt:
  secret: ""
  refreshSecret: ""
  accessTokenExpireDuration: 1440
  refreshTokenExpireDuration: 60
